=== nirchacham/TranspoolDesktopApp/Transpool/engine/src/resources/transpool.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="TransPoolTrip">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Owner"/>
				<xs:element ref="Capacity"/>
				<xs:element ref="PPK"/>
				<xs:element ref="Route"/>
				<xs:element ref="Scheduling"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TransPool">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MapDescriptor"/>
				<xs:element ref="PlannedTrips" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Stops">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Stop" minOccurs="2" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Stop">
		<xs:complexType>
			<xs:attribute name="y" type="xs:int" use="required"/>
			<xs:attribute name="x" type="xs:int" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SpeedLimit" type="xs:int"/>
	<xs:element name="Scheduling">
		<xs:complexType>
			<xs:attribute name="recurrences" default="OneTime">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="OneTime"/>
						<xs:enumeration value="Daily"/>
						<xs:enumeration value="BiDaily"/>
						<xs:enumeration value="Weekly"/>
						<xs:enumeration value="Monthly"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="hour-start" type="xs:int" use="required"/>
			<xs:attribute name="day-start" type="xs:int"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Route">
		<xs:complexType>
			<xs:attribute name="path" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PlannedTrips">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="TransPoolTrip"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Paths">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Path" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Path">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Length"/>
				<xs:element ref="FuelConsumption"/>
				<xs:element ref="SpeedLimit"/>
			</xs:sequence>
			<xs:attribute name="to" type="xs:string" use="required"/>
			<xs:attribute name="one-way" type="xs:boolean" default="false"/>
			<xs:attribute name="from" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PPK" type="xs:int"/>
	<xs:element name="Owner" type="xs:string"/>
	<xs:element name="MapDescriptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MapBoundries"/>
				<xs:element ref="Stops"/>
				<xs:element ref="Paths"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MapBoundries">
		<xs:complexType>
			<xs:attribute name="width" type="xs:int" use="required"/>
			<xs:attribute name="length" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Length" type="xs:int"/>
	<xs:element name="FuelConsumption" type="xs:int"/>
	<xs:element name="Capacity" type="xs:int"/>
</xs:schema>

=== nirchacham/TranspoolDesktopApp/Transpool/engine/src/resources/ex1-real.xml
<?xml version="1.0" encoding="UTF-8"?>
<TransPool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="transpool.xsd">
	<MapDescriptor>
		<MapBoundries length="20" width="20"/>
		<Stops>
			<Stop name="Park Hayarkon" x="2" y="2"/>
			<Stop name="Independance Garden" x="4" y="4"/>
			<Stop name="Square Hamedina" x="9" y="4"/>
			<Stop name="Bursa" x="12" y="3"/>
			<Stop name="Ayallon Mall" x="16" y="1"/>
			<Stop name="Rabin Square" x="8" y="6"/>
			<Stop name="Azriely Mall" x="10" y="8"/>
			<Stop name="Lagardia" x="11" y="10"/>
			<Stop name="MTA" x="6" y="12"/>
			<Stop name="Yaffa Port" x="2" y="11"/>
			<Stop name="Wolfson train" x="5" y="15"/>
			<Stop name="Grouping Exilse" x="10" y="13"/>
			<Stop name="Saffari" x="15" y="14"/>
			<Stop name="Mesubim" x="15" y="15"/>
			<Stop name="Ganot" x="14" y="17"/>
			<Stop name="Mikve Israel" x="9" y="16"/>
			<Stop name="Holon Mall" x="9" y="18"/>
			<Stop name="HIT" x="7" y="18"/>
			<Stop name="Yoseftal" x="5" y="18"/>
		</Stops>
		<Paths>
			<Path from="Mikve Israel" to="Holon Mall">
				<Length>5</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>60</SpeedLimit>
			</Path>																		
			<Path from="HIT" to="Holon Mall" one-way="true">
				<Length>1</Length>
				<FuelConsumption>4</FuelConsumption>
				<SpeedLimit>12</SpeedLimit>
			</Path>																		
			<Path from="Yoseftal" to="HIT">
				<Length>5</Length>
				<FuelConsumption>6</FuelConsumption>
				<SpeedLimit>60</SpeedLimit>
			</Path>																		
			<Path from="Wolfson train" to="Yoseftal">
				<Length>5</Length>
				<FuelConsumption>12</FuelConsumption>
				<SpeedLimit>60</SpeedLimit>
			</Path>																		
			<Path from="Wolfson train" to="Mikve Israel">
				<Length>6</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>24</SpeedLimit>
			</Path>																		
			<Path from="Ganot" to="Mikve Israel">
				<Length>6</Length>
				<FuelConsumption>10</FuelConsumption>
				<SpeedLimit>18</SpeedLimit>
			</Path>																		
			<Path from="Ganot" to="Grouping Exilse">
				<Length>6</Length>
				<FuelConsumption>12</FuelConsumption>
				<SpeedLimit>72</SpeedLimit>
			</Path>																		
			<Path from="Ganot" to="Mesubim">
				<Length>5</Length>
				<FuelConsumption>12</FuelConsumption>
				<SpeedLimit>30</SpeedLimit>
			</Path>																		
			<Path from="Grouping Exilse" to="Mesubim">
				<Length>10</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>60</SpeedLimit>
			</Path>																		
			<Path from="Mesubim" to="Saffari" one-way="true">
				<Length>1</Length>
				<FuelConsumption>6</FuelConsumption>
				<SpeedLimit>12</SpeedLimit>
			</Path>																		
			<Path from="Ayallon Mall" to="Saffari">
				<Length>14</Length>
				<FuelConsumption>10</FuelConsumption>
				<SpeedLimit>28</SpeedLimit>
			</Path>																
			<Path from="Wolfson train" to="Yaffa Port" one-way="true">
				<Length>4</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>16</SpeedLimit>
			</Path>																
			<Path from="MTA" to="Wolfson train">
				<Length>3</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>12</SpeedLimit>
			</Path>														
			<Path from="Mikve Israel" to="Grouping Exilse">
				<Length>3</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>9</SpeedLimit>
			</Path>												
			<Path from="Lagardia" to="Grouping Exilse">
				<Length>2</Length>
				<FuelConsumption>12</FuelConsumption>
				<SpeedLimit>24</SpeedLimit>
			</Path>										
			<Path from="Yaffa Port" to="MTA" one-way="true">
				<Length>6</Length>
				<FuelConsumption>6</FuelConsumption>
				<SpeedLimit>72</SpeedLimit>
			</Path>										
			<Path from="MTA" to="Lagardia">
				<Length>4</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>12</SpeedLimit>
			</Path>										
			<Path from="Azriely Mall" to="Lagardia">
				<Length>4</Length>
				<FuelConsumption>12</FuelConsumption>
				<SpeedLimit>16</SpeedLimit>
			</Path>								
			<Path from="Rabin Square" to="MTA">
				<Length>8</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>32</SpeedLimit>
			</Path>						
			<Path from="Azriely Mall" to="Bursa">
				<Length>10</Length>
				<FuelConsumption>8</FuelConsumption>
				<SpeedLimit>60</SpeedLimit>
			</Path>				
			<Path from="Azriely Mall" to="Rabin Square">
				<Length>5</Length>
				<FuelConsumption>5</FuelConsumption>
				<SpeedLimit>30</SpeedLimit>
			</Path>				
			<Path from="Square Hamedina" to="Rabin Square">
				<Length>5</Length>
				<FuelConsumption>5</FuelConsumption>
				<SpeedLimit>30</SpeedLimit>
			</Path>
			<Path from="Bursa" to="Ayallon Mall">
				<Length>5</Length>
				<FuelConsumption>6</FuelConsumption>
				<SpeedLimit>60</SpeedLimit>
			</Path>		
			<Path from="Bursa" to="Square Hamedina">
				<Length>8</Length>
				<FuelConsumption>6</FuelConsumption>
				<SpeedLimit>24</SpeedLimit>
			</Path>					
			<Path from="Park Hayarkon" to="Square Hamedina">
				<Length>16</Length>
				<FuelConsumption>10</FuelConsumption>
				<SpeedLimit>64</SpeedLimit>
			</Path>
			<Path from="Square Hamedina" to="Independance Garden">
				<Length>14</Length>
				<FuelConsumption>10</FuelConsumption>
				<SpeedLimit>84</SpeedLimit>
			</Path>
		</Paths>
	</MapDescriptor>
	<PlannedTrips>	
		<TransPoolTrip>
			<Owner>Purpule</Owner>
			<Capacity>4</Capacity>
			<PPK>20</PPK>
			<Route path="Rabin Square,Azriely Mall,Lagardia,Grouping Exilse,Mikve Israel,Ganot,Mesubim,Saffari"/>
			<Scheduling hour-start="10"/>
		</TransPoolTrip>		
		<TransPoolTrip>
			<Owner>Blue</Owner>
			<Capacity>4</Capacity>
			<PPK>50</PPK>
				<Route path="HIT,Holon Mall,Mikve Israel,Grouping Exilse,Mesubim,Saffari,Ayallon Mall,Bursa,Square Hamedina,Independance Garden"/>
			<Scheduling hour-start="14"/>
		</TransPoolTrip>	
		<TransPoolTrip>
			<Owner>Green</Owner>
			<Capacity>3</Capacity>
			<PPK>10</PPK>
			<Route path="Yoseftal,Wolfson train,MTA,Rabin Square"/>
			<Scheduling hour-start="13"/>
		</TransPoolTrip>	
		<TransPoolTrip>
			<Owner>Orange</Owner>
			<Capacity>4</Capacity>
			<PPK>20</PPK>
			<Route path="HIT,Yoseftal,Wolfson train,MTA,Lagardia,Azriely Mall, Rabin Square,Square Hamedina,Park Hayarkon"/>
			<Scheduling hour-start="7"/>
		</TransPoolTrip>
		<TransPoolTrip>
			<Owner>Red</Owner>
			<Capacity>3</Capacity>
			<PPK>25</PPK>
			<Route path="Wolfson train,Yaffa Port,MTA,Lagardia,Azriely Mall,Bursa,Square Hamedina,Park Hayarkon"/>
			<Scheduling hour-start="8"/>
		</TransPoolTrip>
	</PlannedTrips>
</TransPool>

=== nirchacham/TranspoolDesktopApp/Transpool/src/resources/master.xml
<?xml version="1.0" encoding="UTF-8"?>
<TransPool xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="transpool.xsd">
	<MapDescriptor>
		<MapBoundries length="10" width="10"/>
		<Stops>
			<Stop name="A" x="3" y="4"/>
			<Stop name="B" x="1" y="2"/>
			<Stop name="C" x="7" y="3"/>
		</Stops>
		<Paths>
			<Path from="A" to="B">
				<Length>20</Length>
				<FuelConsumption>10</FuelConsumption>
				<SpeedLimit>80</SpeedLimit>
			</Path>
			<Path from="B" to="C" one-way="true">
				<Length>15</Length>
				<FuelConsumption>5</FuelConsumption>
				<SpeedLimit>40</SpeedLimit>
			</Path>
		</Paths>
	</MapDescriptor>
	<PlannedTrips>
		<TransPoolTrip>
			<Owner>Mosh</Owner>
			<Capacity>3</Capacity>
			<PPK>20</PPK>
			<Route path="A,B,C"/>
			<Scheduling hour-start="10" day-start="2" recurrences="Daily"/>
		</TransPoolTrip>
	</PlannedTrips>
</TransPool>
